---

- name: Setting up
  hosts: all
  become: yes
  roles:
    - ping
    - create-user
    - k8s-prerequisite

- name: kube master
  hosts: master
  become: yes
  # become_user: ubuntu
  roles:
    - k8s-master

- name: set fact join_command to master host
  hosts: master
  become: yes
  become_user: ubuntu
  gather_facts: true
  tasks:
    - name: get joind command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- name: kube slave
  hosts: node
  become: yes
  #become_user: ubuntu
  tasks:
    - name: TCP port 6443 on master is reachable from worker
      debug: 
        msg: "{{hostvars[groups['master'][0]].join_command}}"
        #wait_for: "host={{ hostvars['master']['ansible_default_ipv4']['address'] }} port=6443 timeout=1"
        
      
    - name: join cluster
      shell: "{{ hostvars[groups['master'][0]].join_command }} >> node_joined.txt"
      args:
        chdir: /home/ubuntu
        creates: node_joined.txt


